/* Generated by AN DISI Unibo */ 
package it.unibo.ioport

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Ioport ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var displayMessage = "System Ready"
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("ioport | STARTED - AUTO-DEMO WORKFLOW ENABLED")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="delay_avvio", cond=doswitch() )
				}	 
				state("delay_avvio") { //this:State
					action { //it:State
						CommUtils.outmagenta("ioport | In attesa che gli altri attori facciano il boot...")
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="simula_pressione_bottone", cond=doswitch() )
				}	 
				state("display_idle") { //this:State
					action { //it:State
						CommUtils.outgreen("ioport | IDLE - Display: '$displayMessage'")
						forward("display_update", "displayUpdate(displayMessage)" ,"cargoservice" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("simula_pressione_bottone") { //this:State
					action { //it:State
						CommUtils.outmagenta("ioport | [TEST] Invio load_request a cargoservice...")
						 displayMessage = "Loading request..."  
						request("load_request", "loadRequest(none)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t111",targetState="accepted",cond=whenReply("load_accepted"))
					transition(edgeName="t112",targetState="retrylater",cond=whenReply("load_retrylater"))
					transition(edgeName="t113",targetState="refused",cond=whenReply("load_refused"))
				}	 
				state("accepted") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadAccepted(SLOTID)"), Term.createTerm("loadAccepted(SLOTID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outgreen("ioport | DISPLAY: load accepted - Il sistema verificherà la presenza del container tramite il sonar")
								 displayMessage = "ACCEPTED - Placing container..."  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="transfer_in_progress", cond=doswitch() )
				}	 
				state("retrylater") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadRetryLater(none)"), Term.createTerm("loadRetryLater(none)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outyellow("ioport | DISPLAY: retry later")
								 displayMessage = "RETRY LATER"  
						}
						CommUtils.outmagenta("ioport | [TEST] Hold momentaneamente occupata, attendo 3s e riprovo...")
						delay(3000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="simula_pressione_bottone", cond=doswitch() )
				}	 
				state("refused") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadRefused(none)"), Term.createTerm("loadRefused(none)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outred("ioport | DISPLAY: load refused (hold is full)")
								 displayMessage = "REFUSED - Hold Full"  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="display_idle", cond=doswitch() )
				}	 
				state("transfer_in_progress") { //this:State
					action { //it:State
						CommUtils.outcyan("ioport | DISPLAY: Transfer in progress")
						 displayMessage = "Service working"  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t314",targetState="transfer_complete",cond=whenDispatch("robot_complete_notification"))
				}	 
				state("transfer_complete") { //this:State
					action { //it:State
						CommUtils.outgreen("ioport | DISPLAY: Transfer complete - Ready")
						 displayMessage = "Transfer complete - Ready"  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="display_idle", cond=doswitch() )
				}	 
			}
		}
} 
