# Porta standard MQTT
listener 1883
protocol mqtt

# Porta per i WebSocket (necessaria per il tuo ioport.html)
listener 9001
protocol websockets

# Permetti connessioni anonime (senza username e password)
allow_anonymous true