/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var CurrentSlot = ""
		        var StepTime    = 350
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargorobot | STARTED (Wrapper di robotsmart26)")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargorobot | waiting for robot_transfer requests...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t018",targetState="handle_transfer",cond=whenRequest("robot_transfer"))
				}	 
				state("handle_transfer") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("robotTransfer(SLOT)"), Term.createTerm("robotTransfer(SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurrentSlot = payloadArg(0).toString()  
								CommUtils.outmagenta("cargorobot | Tappa 1/3: Spostamento verso IOPort (4,1)")
								request("moverobot", "moverobot(4,1,$StepTime)" ,"robotsmart" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t0_reply19",targetState="go_to_slot5",cond=whenReply("moverobotdone"))
					transition(edgeName="t0_reply20",targetState="handle_move_failed",cond=whenReply("moverobotfailed"))
				}	 
				state("go_to_slot5") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargorobot | Container prelevato. Tappa 2/3: Spostamento verso SLOT5 (2,5) per etichettatura")
						request("moverobot", "moverobot(2,5,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t1_reply21",targetState="go_to_final_slot",cond=whenReply("moverobotdone"))
					transition(edgeName="t1_reply22",targetState="handle_move_failed",cond=whenReply("moverobotfailed"))
				}	 
				state("go_to_final_slot") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargorobot | Etichettatura completata. Tappa 3/3: Spostamento verso lo slot riservato ($CurrentSlot)")
						
						            var TargetX = 0
						            var TargetY = 0
						        
						            if(CurrentSlot == "slot1") { TargetX = 1; TargetY = 1 }
						            else if(CurrentSlot == "slot2") { TargetX = 1; TargetY = 3 }
						            else if(CurrentSlot == "slot3") { TargetX = 4; TargetY = 3 }
						            else if(CurrentSlot == "slot4") { TargetX = 4; TargetY = 5 }
						request("moverobot", "moverobot($TargetX,$TargetY,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t2_reply23",targetState="complete_transfer",cond=whenReply("moverobotdone"))
					transition(edgeName="t2_reply24",targetState="handle_move_failed",cond=whenReply("moverobotfailed"))
				}	 
				state("complete_transfer") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargorobot | Container depositato nello slot di destinazione con successo!")
						answer("robot_transfer", "robot_complete", "robotComplete(ok)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="return_home", cond=doswitch() )
				}	 
				state("return_home") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargorobot | Ritorno alla posizione HOME (0,0)")
						request("moverobot", "moverobot(0,0,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t325",targetState="waiting",cond=whenReply("moverobotdone"))
					transition(edgeName="t326",targetState="waiting",cond=whenReply("moverobotfailed"))
				}	 
				state("handle_move_failed") { //this:State
					action { //it:State
						CommUtils.outred("cargorobot | ERRORE FATALE: Il robot ha fallito un movimento!")
						answer("robot_transfer", "robot_failed", "robotFailed(obstacle)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
			}
		}
} 
