/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		var CurrentSlot = ""
		var StepTime    = 350
		var TargetX     = 0 
		var TargetY     = 0 
		var TargetX_forRelease = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargorobot | avviato (Wrapper di robotsmart26)")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("waiting") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargorobot | in attesa di richieste di movimento...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t022",targetState="handle_ioport",cond=whenRequest("robot_to_ioport"))
					transition(edgeName="t023",targetState="handle_slot5",cond=whenRequest("robot_to_slot5"))
					transition(edgeName="t024",targetState="handle_final_slot",cond=whenRequest("robot_to_slot"))
				}	 
				state("handle_ioport") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargorobot | Tappa 1/3: Spostamento verso IOPort (4,1)")
						request("moverobot", "moverobot(4,1,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t125",targetState="ioport_success",cond=whenReply("moverobotdone"))
					transition(edgeName="t126",targetState="ioport_failed",cond=whenReply("moverobotfailed"))
				}	 
				state("ioport_success") { //this:State
					action { //it:State
						answer("robot_to_ioport", "robot_ioport_done", "robotIoportDone(none)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("ioport_failed") { //this:State
					action { //it:State
						CommUtils.outred("cargorobot | ERRORE FATALE: Spostamento a IOPort fallito!")
						answer("robot_to_ioport", "robot_ioport_failed", "robotIoportFailed(obstacle)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("handle_slot5") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargorobot | Tappa 2/3: Spostamento verso SLOT5 (2,5) per etichettatura")
						request("moverobot", "moverobot(2,5,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t227",targetState="slot5_success",cond=whenReply("moverobotdone"))
					transition(edgeName="t228",targetState="slot5_failed",cond=whenReply("moverobotfailed"))
				}	 
				state("slot5_success") { //this:State
					action { //it:State
						answer("robot_to_slot5", "robot_slot5_done", "robotSlot5Done(none)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("slot5_failed") { //this:State
					action { //it:State
						CommUtils.outred("cargorobot | ERRORE FATALE: Spostamento a SLOT5 fallito!")
						answer("robot_to_slot5", "robot_slot5_failed", "robotSlot5Failed(obstacle)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("handle_final_slot") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("robotToSlot(SLOT)"), Term.createTerm("robotToSlot(SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurrentSlot = payloadArg(0).toString()  
						}
						CommUtils.outmagenta("cargorobot | Tappa 3/3: richiedo posizione fisica per $CurrentSlot alla hold")
						request("find_slot_position", "findSlotPosition($CurrentSlot)" ,"hold" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t3a29",targetState="move_to_final_slot",cond=whenReply("slot_position"))
				}	 
				state("move_to_final_slot") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("slotPosition(POSX,POSY)"), Term.createTerm("slotPosition(POSX,POSY)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								            TargetX = payloadArg(0).toInt()
								            TargetY = payloadArg(1).toInt()
								            TargetX_forRelease = TargetX + 1
						}
						CommUtils.outmagenta("cargorobot | Spostamento verso ($TargetX_forRelease,$TargetY)")
						request("moverobot", "moverobot($TargetX_forRelease,$TargetY,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t330",targetState="final_slot_success",cond=whenReply("moverobotdone"))
					transition(edgeName="t331",targetState="final_slot_failed",cond=whenReply("moverobotfailed"))
				}	 
				state("final_slot_success") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargorobot | Container depositato nello slot di destinazione con successo!")
						answer("robot_to_slot", "robot_slot_done", "robotSlotDone(none)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="return_home", cond=doswitch() )
				}	 
				state("final_slot_failed") { //this:State
					action { //it:State
						CommUtils.outred("cargorobot | ERRORE FATALE: Spostamento allo slot di destinazione fallito!")
						answer("robot_to_slot", "robot_slot_failed", "robotSlotFailed(obstacle)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting", cond=doswitch() )
				}	 
				state("return_home") { //this:State
					action { //it:State
						CommUtils.outmagenta("cargorobot | Ritorno alla posizione HOME (0,0)")
						request("moverobot", "moverobot(0,0,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t432",targetState="waiting",cond=whenReply("moverobotdone"))
					transition(edgeName="t433",targetState="waiting",cond=whenReply("moverobotfailed"))
				}	 
			}
		}
} 
