/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var ioPortOccupied = false
		        var CurrentSlot = ""
		        var ContainerDetected = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("cargoservice | started")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("disengaged") { //this:State
					action { //it:State
						CommUtils.outgreen("cargoservice | waiting for load request")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="handle_load_request",cond=whenRequest("load_request"))
				}	 
				state("handle_load_request") { //this:State
					action { //it:State
						CommUtils.outcyan("ioport -> cargoservice | load request")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="request_slot", cond=doswitchGuarded({ !ioPortOccupied  
					}) )
					transition( edgeName="goto",targetState="refuse_retry_later", cond=doswitchGuarded({! ( !ioPortOccupied  
					) }) )
				}	 
				state("request_slot") { //this:State
					action { //it:State
						request("find_free_slot", "findFreeSlot(none)" ,"hold" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting_for_slot", cond=doswitch() )
				}	 
				state("refuse_retry_later") { //this:State
					action { //it:State
						answer("load_request", "load_retrylater", "loadRetryLater(none)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("waiting_for_slot") { //this:State
					action { //it:State
						CommUtils.outcyan("cargoservice | waiting for slot response")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t16",targetState="slot_available",cond=whenReply("slot_found"))
					transition(edgeName="t17",targetState="hold_is_full",cond=whenReply("slot_full"))
				}	 
				state("slot_available") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("slotFound(SLOTID)"), Term.createTerm("slotFound(SLOTID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
									            CurrentSlot = payloadArg(0).toString()
									            ioPortOccupied = true
								CommUtils.outgreen("cargoservice | reserved $CurrentSlot")
								answer("load_request", "load_accepted", "loadAccepted($CurrentSlot)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged", cond=doswitch() )
				}	 
				state("hold_is_full") { //this:State
					action { //it:State
						CommUtils.outred("cargoservice | hold is full")
						answer("load_request", "load_refused", "loadRefused(none)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
				state("engaged") { //this:State
					action { //it:State
						CommUtils.outyellow("cargoservice | waiting for container - Interrogo il sonar...")
						forward("led_blink", "ledBlink(on)" ,"led" ) 
						request("check_distance", "checkDistance(none)" ,"sonar" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t28",targetState="evaluate_distance",cond=whenReply("distance_response"))
				}	 
				state("evaluate_distance") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distanceResponse(DISTANCE)"), Term.createTerm("distanceResponse(DISTANCE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val Dist = payloadArg(0).toString().toInt()
								                ContainerDetected = Dist < 80 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="container_arrived", cond=doswitchGuarded({ ContainerDetected  
					}) )
					transition( edgeName="goto",targetState="retry_check", cond=doswitchGuarded({! ( ContainerDetected  
					) }) )
				}	 
				state("retry_check") { //this:State
					action { //it:State
						CommUtils.outyellow("cargoservice | Container non ancora rilevato. Riprovo tra 2 secondi...")
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged", cond=doswitch() )
				}	 
				state("container_arrived") { //this:State
					action { //it:State
						CommUtils.outgreen("cargoservice | Container detected via Sonar - requesting robot transfer")
						request("robot_transfer", "robotTransfer($CurrentSlot)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t39",targetState="on_robot_completed",cond=whenReply("robot_complete"))
				}	 
				state("on_robot_completed") { //this:State
					action { //it:State
						forward("led_blink", "ledBlink(off)" ,"led" ) 
						request("find_occupy", "occupySlot($CurrentSlot)" ,"hold" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t410",targetState="finalize_load_ok",cond=whenReply("occupy_done"))
				}	 
				state("finalize_load_ok") { //this:State
					action { //it:State
						
						            ioPortOccupied = false
						            var SlotSend = CurrentSlot
						            CurrentSlot = ""
						CommUtils.outgreen("cargoservice | transfer completed and slot occupied")
						forward("robot_complete_notification", "robotCompleteNotif($SlotSend)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="disengaged", cond=doswitch() )
				}	 
			}
		}
} 
