/* Generated by AN DISI Unibo */ 
package it.unibo.hold

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Hold ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        val slots = mutableMapOf(
		            "slot1" to "free",
		            "slot2" to "free",
		            "slot3" to "free",
		            "slot4" to "free"
		        )
		        var reservedSlot = ""
		        var slotIsAvailable = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("hold | started")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						CommUtils.outgreen("hold | IDLE")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="find_slot_logic",cond=whenRequest("find_free_slot"))
					transition(edgeName="t01",targetState="occupy_slot",cond=whenRequest("find_occupy"))
					transition(edgeName="t02",targetState="free_slot",cond=whenRequest("find_release"))
				}	 
				state("find_slot_logic") { //this:State
					action { //it:State
						
						            val freeSlot = slots.filter { it.value == "free" }.keys.firstOrNull()
						            slotIsAvailable = freeSlot != null
						            if (slotIsAvailable) {
						                slots[freeSlot!!] = "reserved"
						                reservedSlot = freeSlot!!
						            } else {
						                reservedSlot = ""
						            }
						if(  slotIsAvailable  
						 ){forward("slot_is_free", "slot_is_free(none)" ,"hold" ) 
						}
						else
						 {forward("slot_is_full", "slot_is_full(none)" ,"hold" ) 
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t0b3",targetState="respond_slot_found",cond=whenDispatch("slot_is_free"))
					transition(edgeName="t0b4",targetState="respond_slot_full",cond=whenDispatch("slot_is_full"))
				}	 
				state("respond_slot_found") { //this:State
					action { //it:State
						CommUtils.outcyan("hold | Responding: slot $reservedSlot found")
						answer("find_free_slot", "slot_found", "slotFound(reservedSlot)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("respond_slot_full") { //this:State
					action { //it:State
						CommUtils.outred("hold | Responding: hold is FULL")
						answer("find_free_slot", "slot_full", "slotFull(none)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("occupy_slot") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("occupySlot(SLOTID)"), Term.createTerm("occupySlot(SLOTID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								                val SlotToOccupy = payloadArg(0)
								                if (slots[SlotToOccupy] == "reserved" || slots[SlotToOccupy] == "free") {
								                    slots[SlotToOccupy] = "occupied" 
								                }
								CommUtils.outgreen("hold | $SlotToOccupy now OCCUPIED")
								answer("find_occupy", "occupy_done", "occupySlotDone(none)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("free_slot") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("releaseSlot(SLOTID)"), Term.createTerm("releaseSlot(SLOTID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								                val SlotToRelease = payloadArg(0)
								                slots[SlotToRelease] = "free" 
								CommUtils.outyellow("hold | Released $SlotToRelease")
								answer("find_release", "release_done", "releaseSlotDone(none)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
