/* Generated by AN DISI Unibo */ 
package it.unibo.led

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Led ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 var ledState = "off"  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("led | started - LED OFF")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="off", cond=doswitch() )
				}	 
				state("off") { //this:State
					action { //it:State
						CommUtils.outgreen("led | LED OFF")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t024",targetState="handle_initial_blink",cond=whenDispatch("led_blink"))
				}	 
				state("handle_initial_blink") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("ledBlink(STATE)"), Term.createTerm("ledBlink(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 ledState = payloadArg(0)  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="on_blink", cond=doswitchGuarded({ ledState == "on"  
					}) )
					transition( edgeName="goto",targetState="off", cond=doswitchGuarded({! ( ledState == "on"  
					) }) )
				}	 
				state("on_blink") { //this:State
					action { //it:State
						CommUtils.outyellow("led | LED BLINKING (system ENGAGED)")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t125",targetState="handle_toggle",cond=whenDispatch("led_blink"))
				}	 
				state("handle_toggle") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("ledBlink(STATE)"), Term.createTerm("ledBlink(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 ledState = payloadArg(0)  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="off", cond=doswitchGuarded({ ledState == "off"  
					}) )
					transition( edgeName="goto",targetState="on_blink", cond=doswitchGuarded({! ( ledState == "off"  
					) }) )
				}	 
			}
		}
} 
