/* Generated by AN DISI Unibo */ 
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonar ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        val DFREE = 80
		        var Distance = 50
		        var failureCounter = 0
		        var distanceExceeded = false
		        var criticalFailure = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("sonar | started")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="monitoring", cond=doswitch() )
				}	 
				state("monitoring") { //this:State
					action { //it:State
						
							        distanceExceeded = Distance > DFREE
							        criticalFailure = failureCounter >= 3
						if(  criticalFailure  
						 ){forward("sonar_alert", "sonar_alert(none)" ,"sonar" ) 
						}
						else
						 {if(  distanceExceeded  
						  ){forward("sonar_warn", "sonar_warn(none)" ,"sonar" ) 
						 }
						 else
						  {forward("sonar_normal", "sonar_normal(none)" ,"sonar" ) 
						  }
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("normal_status") { //this:State
					action { //it:State
						CommUtils.outgreen("sonar | Distance OK")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_normal_status", 
				 	 					  scope, context!!, "local_tout_"+name+"_normal_status", 5000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t129",targetState="monitoring",cond=whenTimeout("local_tout_"+name+"_normal_status"))   
				}	 
				state("warning_status") { //this:State
					action { //it:State
						CommUtils.outyellow("sonar | WARNING")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_warning_status", 
				 	 					  scope, context!!, "local_tout_"+name+"_warning_status", 5000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t230",targetState="monitoring",cond=whenTimeout("local_tout_"+name+"_warning_status"))   
				}	 
				state("alert_status") { //this:State
					action { //it:State
						CommUtils.outred("sonar | ALERT")
						forward("sensor_data", "sensorData($Distance)" ,"cargoservice" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_alert_status", 
				 	 					  scope, context!!, "local_tout_"+name+"_alert_status", 5000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t331",targetState="monitoring",cond=whenTimeout("local_tout_"+name+"_alert_status"))   
				}	 
			}
		}
} 
